---
- name: build-essential....
  become: yes
  become_user: root
  package: name=build-essential state=present

- name: emacs24 build-deps
  become: yes
  become_user: root
  package: name=emacs24 state=build-dep

- name: downloading...
  become: yes
  become_user: root
  get_url: >
    url={{emacs_build_url}}
    dest=/tmp/{{emacs_build_tgz}}
    mode=0644
    timeout={{emacs_build_timeout_seconds}}

- name: unarchiving...
  become: yes
  become_user: root
  unarchive: >
    copy=no
    src=/tmp/{{emacs_build_tgz}}
    dest=/opt
    creates=/opt/{{emacs_name}}

- name: configuring...
  become: yes
  become_user: root
  command: ./configure
  args:
    chdir: /opt/{{emacs_name}}
    creates: /opt/{{emacs_name}}/Makefile

- name: building...
  become: yes
  become_user: root
  command: make
  args:
    chdir: /opt/{{emacs_name}}
    creates: /opt/{{emacs_name}}/src/emacs

- name: installing...
  become: yes
  become_user: root
  command: make install
  args:
    chdir: /opt/{{emacs_name}}
    creates: /usr/local/bin/emacs
